//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class generales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal generales() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.generales", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente.
        /// </summary>
        internal static string estadoContrato {
            get {
                return ResourceManager.GetString("estadoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a btnagregar.
        /// </summary>
        internal static string imgAgregar {
            get {
                return ResourceManager.GetString("imgAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a btnbuscar.
        /// </summary>
        internal static string imgBuscar {
            get {
                return ResourceManager.GetString("imgBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a btncancelar.
        /// </summary>
        internal static string imgCancelar {
            get {
                return ResourceManager.GetString("imgCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a btncerraralert.
        /// </summary>
        internal static string imgCerrar {
            get {
                return ResourceManager.GetString("imgCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../img/en/btn_remove.png.
        /// </summary>
        internal static string imgEliminarUS {
            get {
                return ResourceManager.GetString("imgEliminarUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a btngrabar.
        /// </summary>
        internal static string imgGrabar {
            get {
                return ResourceManager.GetString("imgGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../img/en/btn_save.png.
        /// </summary>
        internal static string imgGrabarUS {
            get {
                return ResourceManager.GetString("imgGrabarUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a btnlimpiar.
        /// </summary>
        internal static string imgLimpiar {
            get {
                return ResourceManager.GetString("imgLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a btnmodificar2.
        /// </summary>
        internal static string imgModificar {
            get {
                return ResourceManager.GetString("imgModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a btnno.
        /// </summary>
        internal static string imgNo {
            get {
                return ResourceManager.GetString("imgNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a btnnuevo.
        /// </summary>
        internal static string imgNuevo {
            get {
                return ResourceManager.GetString("imgNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a btnsi.
        /// </summary>
        internal static string imgSi {
            get {
                return ResourceManager.GetString("imgSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- All --.
        /// </summary>
        internal static string testoAll {
            get {
                return ResourceManager.GetString("testoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Seleccionar --.
        /// </summary>
        internal static string textoSeleccionar {
            get {
                return ResourceManager.GetString("textoSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Selection --.
        /// </summary>
        internal static string textoSelect {
            get {
                return ResourceManager.GetString("textoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Todos --.
        /// </summary>
        internal static string textoTodos {
            get {
                return ResourceManager.GetString("textoTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agri.
        /// </summary>
        internal static string txtAgri {
            get {
                return ResourceManager.GetString("txtAgri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hidro.
        /// </summary>
        internal static string txtHidro {
            get {
                return ResourceManager.GetString("txtHidro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mixto.
        /// </summary>
        internal static string txtMixto {
            get {
                return ResourceManager.GetString("txtMixto", resourceCulture);
            }
        }
    }
}
